export const countryFlags: { [key: string]: string } = {
  // 亚洲国家
  'China': '🇨🇳',
  'Japan': '🇯🇵',
  'South Korea': '🇰🇷',
  'India': '🇮🇳',
  'Indonesia': '🇮🇩',
  'Malaysia': '🇲🇾',
  'Philippines': '🇵🇭',
  'Singapore': '🇸🇬',
  'Thailand': '🇹🇭',
  'Vietnam': '🇻🇳',
  'Turkey': '🇹🇷',
  'Saudi Arabia': '🇸🇦',
  'United Arab Emirates': '🇦🇪',
  'Israel': '🇮🇱',
  'Iran': '🇮🇷',
  'Iraq': '🇮🇶',
  'Kazakhstan': '🇰🇿',
  'Pakistan': '🇵🇰',
  'Bangladesh': '🇧🇩',
  'Afghanistan': '🇦🇫',
  'Uzbekistan': '🇺🇿',
  'Maldives': '🇲🇻',
  'Kyrgyzstan': '🇰🇬',
  'Tajikistan': '🇹🇯',
  'Turkmenistan': '🇹🇲',
  'Jordan': '🇯🇴',
  'Kuwait': '🇰🇼',
  'Lebanon': '🇱🇧',
  'Oman': '🇴🇲',
  'Qatar': '🇶🇦',
  'Yemen': '🇾🇪',
  'Syria': '🇸🇾',
  'Palestine': '🇵🇸',
  'Mongolia': '🇲🇳',
  'Nepal': '🇳🇵',
  'Sri Lanka': '🇱🇰',
  'Myanmar': '🇲🇲',
  'Cambodia': '🇰🇭',
  'Laos': '🇱🇦',
  'Brunei': '🇧🇳',
  'East Timor': '🇹🇱',
  'Bhutan': '🇧🇹',
  'North Korea': '🇰🇵',
  'Hong Kong': '🇭🇰',
  'Taiwan': '🇹🇼',
  'Macau': '🇲🇴',
  
  // 欧洲国家
  'United Kingdom': '🇬🇧',
  'France': '🇫🇷',
  'Germany': '🇩🇪',
  'Italy': '🇮🇹',
  'Spain': '🇪🇸',
  'Russia': '🇷🇺',
  'Netherlands': '🇳🇱',
  'Sweden': '🇸🇪',
  'Switzerland': '🇨🇭',
  'Poland': '🇵🇱',
  'Belgium': '🇧🇪',
  'Austria': '🇦🇹',
  'Norway': '🇳🇴',
  'Denmark': '🇩🇰',
  'Finland': '🇫🇮',
  'Ireland': '🇮🇪',
  'Portugal': '🇵🇹',
  'Greece': '🇬🇷',
  'Ukraine': '🇺🇦',
  'Czech Republic': '🇨🇿',
  'Romania': '🇷🇴',
  'Hungary': '🇭🇺',
  'Belarus': '🇧🇾',
  'Bulgaria': '🇧🇬',
  'Iceland': '🇮🇸',
  'Croatia': '🇭🇷',
  'Serbia': '🇷🇸',
  'Slovakia': '🇸🇰',
  'Bosnia and Herzegovina': '🇧🇦',
  'Estonia': '🇪🇪',
  'Latvia': '🇱🇻',
  'Lithuania': '🇱🇹',
  'Slovenia': '🇸🇮',
  'North Macedonia': '🇲🇰',
  'Albania': '🇦🇱',
  'Luxembourg': '🇱🇺',
  'Malta': '🇲🇹',
  'Liechtenstein': '🇱🇮',
  'San Marino': '🇸🇲',
  'Andorra': '🇦🇩',
  'Monaco': '🇲🇨',
  'Vatican City': '🇻🇦',
  'Montenegro': '🇲🇪',
  'Moldova': '🇲🇩',
  'Cyprus': '🇨🇾',
  
  // 北美洲国家
  'United States': '🇺🇸',
  'Canada': '🇨🇦',
  'Mexico': '🇲🇽',
  'Guatemala': '🇬🇹',
  'Belize': '🇧🇿',
  'El Salvador': '🇸🇻',
  'Honduras': '🇭🇳',
  'Nicaragua': '🇳🇮',
  'Costa Rica': '🇨🇷',
  'Panama': '🇵🇦',
  'Bahamas': '🇧🇸',
  'Cuba': '🇨🇺',
  'Jamaica': '🇯🇲',
  'Haiti': '🇭🇹',
  'Dominican Republic': '🇩🇴',
  'Dominica': '🇩🇲',
  'St. Lucia': '🇱🇨',
  'St. Vincent and the Grenadines': '🇻🇨',
  'Grenada': '🇬🇩',
  'Antigua and Barbuda': '🇦🇬',
  'St. Kitts and Nevis': '🇰🇳',
  'Barbados': '🇧🇧',
  'Trinidad and Tobago': '🇹🇹',
  
  // 南美洲国家
  'Brazil': '🇧🇷',
  'Argentina': '🇦🇷',
  'Colombia': '🇨🇴',
  'Peru': '🇵🇪',
  'Venezuela': '🇻🇪',
  'Chile': '🇨🇱',
  'Ecuador': '🇪🇨',
  'Bolivia': '🇧🇴',
  'Paraguay': '🇵🇾',
  'Uruguay': '🇺🇾',
  'Guyana': '🇬🇾',
  'Suriname': '🇸🇷',
  'French Guiana': '🇬🇫',
  
  // 大洋洲国家
  'Australia': '🇦🇺',
  'New Zealand': '🇳🇿',
  'Fiji': '🇫🇯',
  'Papua New Guinea': '🇵🇬',
  'Solomon Islands': '🇸🇧',
  'Vanuatu': '🇻🇺',
  'Samoa': '🇼🇸',
  'Micronesia': '🇫🇲',
  'Palau': '🇵🇼',
  'Marshall Islands': '🇲🇭',
  'Kiribati': '🇰🇮',
  'Nauru': '🇳🇷',
  'Tuvalu': '🇹🇻',
  'Tonga': '🇹🇴',
  'Cook Islands': '🇨🇰',
  'Niue': '🇳🇺',
  'Tokelau': '🇹🇰',
  'New Caledonia': '🇳🇨',
  'French Polynesia': '🇵🇫',
  'Wallis and Futuna': '🇼🇫',
  'American Samoa': '🇦🇸',
  'Northern Mariana Islands': '🇲🇵',
  'Guam': '🇬🇺',
  
  // 非洲国家
  'South Africa': '🇿🇦',
  'Egypt': '🇪🇬',
  'Algeria': '🇩🇿',
  'Sudan': '🇸🇩',
  'Morocco': '🇲🇦',
  'Angola': '🇦🇴',
  'Mozambique': '🇲🇿',
  'Ghana': '🇬🇭',
  'Madagascar': '🇲🇬',
  'Cameroon': '🇨🇲',
  'Niger': '🇳🇪',
  'Burkina Faso': '🇧🇫',
  'Mali': '🇲🇱',
  'Malawi': '🇲🇼',
  'Zambia': '🇿🇲',
  'Somalia': '🇸🇴',
  'Senegal': '🇸🇳',
  'Chad': '🇹🇩',
  'Zimbabwe': '🇿🇼',
  'Guinea': '🇬🇳',
  'Rwanda': '🇷🇼',
  'Benin': '🇧🇯',
  'Tunisia': '🇹🇳',
  'Burundi': '🇧🇮',
  'Togo': '🇹🇬',
  'Sierra Leone': '🇸🇱',
  'Libya': '🇱🇾',
  'Liberia': '🇱🇷',
  'Central African Republic': '🇨🇫',
  'Mauritania': '🇲🇷',
  'Eritrea': '🇪🇷',
  'Gambia': '🇬🇲',
  'Botswana': '🇧🇼',
  'Namibia': '🇳🇦',
  'Gabon': '🇬🇦',
  'Lesotho': '🇱🇸',
  'Guinea-Bissau': '🇬🇼',
  'Equatorial Guinea': '🇬🇶',
  'Mauritius': '🇲🇺',
  'Eswatini': '🇸🇿',
  'Djibouti': '🇩🇯',
  'Comoros': '🇰🇲',
  'Cabo Verde': '🇨🇻',
  'Sao Tome and Principe': '🇸🇹',
  'Seychelles': '🇸🇨',
  
  // 其他地区
  'Greenland': '🇬🇱',
  'Faroe Islands': '🇫🇴',
  'Åland Islands': '🇦🇽',
  'Gibraltar': '🇬🇮',
  'Isle of Man': '🇮🇲',
  'Jersey': '🇯🇪',
  'Guernsey': '🇬🇬',
  'British Virgin Islands': '🇻🇬',
  'Turks and Caicos Islands': '🇹🇨',
  'Cayman Islands': '🇰🇾',
  'Montserrat': '🇲🇸',
  'Anguilla': '🇦🇮',
  'Bermuda': '🇧🇲',
  'British Indian Ocean Territory': '🇮🇴',
  'Falkland Islands': '🇫🇰',
  'South Georgia and the South Sandwich Islands': '🇬🇸',
  'Christmas Island': '🇨🇽',
  'Cocos Islands': '🇨🇨',
  'Norfolk Island': '🇳🇫',
  'Netherlands Antilles': '🇦🇳',
  'Aruba': '🇦🇼',
  'Curaçao': '🇨🇼',
  'Sint Maarten': '🇸🇽',
  'Bonaire': '🇧🇶',
  'Saint Martin': '🇲🇫',
  'Saint Barthélemy': '🇧🇱',
  'Collectivity of Saint Martin': '🇲🇫',
  'Saint Pierre and Miquelon': '🇵🇲',
  'French Southern Territories': '🇹🇫',
  'Réunion': '🇷🇪',
  'Mayotte': '🇾🇹',
  'Martinique': '🇲🇶',
  'Guadeloupe': '🇬🇵',
  'United States Virgin Islands': '🇻🇮',
  'Puerto Rico': '🇵🇷',
  'U.S. Minor Outlying Islands': '🇺🇲',
  'Heard Island and McDonald Islands': '🇭🇲',
  'Pitcairn Islands': '🇵🇳',
  'British Antarctic Territory': '🇦🇶',
  'Antarctica': '🇦🇶',
  'Western Sahara': '🇪🇭',
  'Kosovo': '🇽🇰',
  'South Sudan': '🇸🇸',
  'Timor-Leste': '🇹🇱',
  
  '_unknown': '🏳'
};

export const getCountryFlag = (country: string): string => {
  return countryFlags[country] || countryFlags['_unknown'];
};