export const countryFlags: { [key: string]: string } = {
  // 亚洲国家
  'China': '🇨🇳',
  'Japan': '🇯🇵',
  'South Korea': '🇰🇷',
  'India': '🇮🇳',
  'Indonesia': '🇮🇩',
  'Malaysia': '🇲🇾',
  'Philippines': '🇵🇭',
  'Singapore': '🇸🇬',
  'Thailand': '🇹🇭',
  'Vietnam': '🇻🇳',
  'Turkey': '🇹🇷',
  'Saudi Arabia': '🇸🇦',
  'United Arab Emirates': '🇦🇪',
  'Israel': '🇮🇱',
  'Iran': '🇮🇷',
  'Iran, Islamic Republic of': '🇮🇷',
  'Iran (Islamic Republic of)': '🇮🇷',
  'Iraq': '🇮🇶',
  'Kazakhstan': '🇰🇿',
  'Pakistan': '🇵🇰',
  'Bangladesh': '🇧🇩',
  'Afghanistan': '🇦🇫',
  'Uzbekistan': '🇺🇿',
  'Maldives': '🇲🇻',
  'Kyrgyzstan': '🇰🇬',
  'Tajikistan': '🇹🇯',
  'Turkmenistan': '🇹🇲',
  'Jordan': '🇯🇴',
  'Kuwait': '🇰🇼',
  'Lebanon': '🇱🇧',
  'Oman': '🇴🇲',
  'Qatar': '🇶🇦',
  'Yemen': '🇾🇪',
  'Syria': '🇸🇾',
  'Syrian Arab Republic': '🇸🇾',
  'Palestine': '🇵🇸',
  'Palestinian Territory': '🇵🇸',
  'Palestine, State of': '🇵🇸',
  'Mongolia': '🇲🇳',
  'Nepal': '🇳🇵',
  'Sri Lanka': '🇱🇰',
  'Myanmar': '🇲🇲',
  'Myanmar/Burma': '🇲🇲',
  'Cambodia': '🇰🇭',
  'Laos': '🇱🇦',
  'Lao People\'s Democratic Republic': '🇱🇦',
  'Brunei': '🇧🇳',
  'Brunei Darussalam': '🇧🇳',
  'East Timor': '🇹🇱',
  'Timor-Leste': '🇹🇱',
  'Bhutan': '🇧🇹',
  'North Korea': '🇰🇵',
  'Hong Kong': '🇭🇰',
  'Hong Kong SAR': '🇭🇰',
  'Hong Kong SAR, China': '🇭🇰',
  'Taiwan': '🇹🇼',
  'Taiwan, Province of China': '🇹🇼',
  'Taiwan (Republic of China)': '🇹🇼',
  'Macau': '🇲🇴',
  'Macao SAR': '🇲🇴',
  'Macao SAR, China': '🇲🇴',
  'Georgia': '🇬🇪',
  'Armenia': '🇦🇲',
  'Azerbaijan': '🇦🇿',
  'Cyprus': '🇨🇾',
  'Bahrain': '🇧🇭',
  
  // 欧洲国家
  'United Kingdom': '🇬🇧',
  'UK': '🇬🇧',
  'Great Britain': '🇬🇧',
  'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Britain': '🇬🇧',
  'France': '🇫🇷',
  'Germany': '🇩🇪',
  'Italy': '🇮🇹',
  'Spain': '🇪🇸',
  'Russia': '🇷🇺',
  'Russian Federation': '🇷🇺',
  'Netherlands': '🇳🇱',
  'Sweden': '🇸🇪',
  'Switzerland': '🇨🇭',
  'Poland': '🇵🇱',
  'Belgium': '🇧🇪',
  'Austria': '🇦🇹',
  'Norway': '🇳🇴',
  'Denmark': '🇩🇰',
  'Finland': '🇫🇮',
  'Ireland': '🇮🇪',
  'Portugal': '🇵🇹',
  'Greece': '🇬🇷',
  'Ukraine': '🇺🇦',
  'Czech Republic': '🇨🇿',
  'Czechia': '🇨🇿',
  'Romania': '🇷🇴',
  'Hungary': '🇭🇺',
  'Belarus': '🇧🇾',
  'Bulgaria': '🇧🇬',
  'Iceland': '🇮🇸',
  'Croatia': '🇭🇷',
  'Serbia': '🇷🇸',
  'Slovakia': '🇸🇰',
  'Bosnia and Herzegovina': '🇧🇦',
  'Bosnia': '🇧🇦',
  'Estonia': '🇪🇪',
  'Latvia': '🇱🇻',
  'Lithuania': '🇱🇹',
  'Slovenia': '🇸🇮',
  'North Macedonia': '🇲🇰',
  'Macedonia': '🇲🇰',
  'FYR Macedonia': '🇲🇰',
  'The former Yugoslav Republic of Macedonia': '🇲🇰',
  'Macedonia, the former Yugoslav Republic of': '🇲🇰',
  'Albania': '🇦🇱',
  'Luxembourg': '🇱🇺',
  'Malta': '🇲🇹',
  'Liechtenstein': '🇱🇮',
  'San Marino': '🇸🇲',
  'Andorra': '🇦🇩',
  'Monaco': '🇲🇨',
  'Vatican City': '🇻🇦',
  'Vatican': '🇻🇦',
  'Montenegro': '🇲🇪',
  'Moldova': '🇲🇩',
  'Moldova, Republic of': '🇲🇩',
  'Republic of Moldova': '🇲🇩',
  'Kosovo': '🇽🇰',
  'Kosovo*': '🇽🇰',
  'Republic of Kosovo': '🇽🇰',
  'Kosovo, Republic of': '🇽🇰',
  
  // 北美洲国家
  'United States': '🇺🇸',
  'USA': '🇺🇸',
  'United States of America': '🇺🇸',
  'America': '🇺🇸',
  'US': '🇺🇸',
  'Canada': '🇨🇦',
  'Mexico': '🇲🇽',
  'Guatemala': '🇬🇹',
  'Belize': '🇧🇿',
  'El Salvador': '🇸🇻',
  'Honduras': '🇭🇳',
  'Nicaragua': '🇳🇮',
  'Costa Rica': '🇨🇷',
  'Panama': '🇵🇦',
  'Bahamas': '🇧🇸',
  'The Bahamas': '🇧🇸',
  'Cuba': '🇨🇺',
  'Jamaica': '🇯🇲',
  'Haiti': '🇭🇹',
  'Dominican Republic': '🇩🇴',
  'Dominican Rep.': '🇩🇴',
  'Dominica': '🇩🇲',
  'St. Lucia': '🇱🇨',
  'Saint Lucia': '🇱🇨',
  'St. Vincent and the Grenadines': '🇻🇨',
  'Saint Vincent and the Grenadines': '🇻🇨',
  'St. Vincent': '🇻🇨',
  'Grenada': '🇬🇩',
  'Antigua and Barbuda': '🇦🇬',
  'St. Kitts and Nevis': '🇰🇳',
  'Saint Kitts and Nevis': '🇰🇳',
  'St. Kitts': '🇰🇳',
  'Barbados': '🇧🇧',
  'Trinidad and Tobago': '🇹🇹',
  
  // 南美洲国家
  'Brazil': '🇧🇷',
  'Argentina': '🇦🇷',
  'Colombia': '🇨🇴',
  'Peru': '🇵🇪',
  'Venezuela': '🇻🇪',
  'Venezuela, Bolivarian Republic of': '🇻🇪',
  'Bolivarian Republic of Venezuela': '🇻🇪',
  'Chile': '🇨🇱',
  'Ecuador': '🇪🇨',
  'Bolivia': '🇧🇴',
  'Bolivia, Plurinational State of': '🇧🇴',
  'Plurinational State of Bolivia': '🇧🇴',
  'Paraguay': '🇵🇾',
  'Uruguay': '🇺🇾',
  'Guyana': '🇬🇾',
  'Suriname': '🇸🇷',
  'French Guiana': '🇬🇫',
  'French Guiana (Guyane)': '🇬🇫',
  'Guyane': '🇬🇫',
  'Falkland Islands': '🇫🇰',
  'Falkland Islands (Malvinas)': '🇫🇰',
  'Falkland Islands [Islas Malvinas]': '🇫🇰',
  
  // 大洋洲国家
  'Australia': '🇦🇺',
  'New Zealand': '🇳🇿',
  'Fiji': '🇫🇯',
  'Papua New Guinea': '🇵🇬',
  'Solomon Islands': '🇸🇧',
  'Vanuatu': '🇻🇺',
  'Samoa': '🇼🇸',
  'Micronesia': '🇫🇲',
  'Micronesia, Federated States of': '🇫🇲',
  'Palau': '🇵🇼',
  'Marshall Islands': '🇲🇭',
  'Kiribati': '🇰🇮',
  'Nauru': '🇳🇷',
  'Tuvalu': '🇹🇻',
  'Tonga': '🇹🇴',
  'Cook Islands': '🇨🇰',
  'Cook Islands (Kūki \'Āirani)': '🇨🇰',
  'Kūki \'Āirani': '🇨🇰',
  'Niue': '🇳🇺',
  'Tokelau': '🇹🇰',
  'Tokelau Islands': '🇹🇰',
  'New Caledonia': '🇳🇨',
  'New Caledonia (Nouvelle-Calédonie)': '🇳🇨',
  'Nouvelle-Calédonie': '🇳🇨',
  'French Polynesia': '🇵🇫',
  'Polynesia': '🇵🇫',
  'Wallis and Futuna': '🇼🇫',
  'Wallis and Futuna Islands': '🇼🇫',
  'Wallis & Futuna': '🇼🇫',
  'American Samoa': '🇦🇸',
  'American Samoa (Amerika Sāmoa)': '🇦🇸',
  'Amerika Sāmoa': '🇦🇸',
  'Northern Mariana Islands': '🇲🇵',
  'Northern Mariana Islands (NMI)': '🇲🇵',
  'NMI': '🇲🇵',
  'Guam': '🇬🇺',
  
  // 非洲国家
  'South Africa': '🇿🇦',
  'Egypt': '🇪🇬',
  'Algeria': '🇩🇿',
  'Sudan': '🇸🇩',
  'Morocco': '🇲🇦',
  'Angola': '🇦🇴',
  'Mozambique': '🇲🇿',
  'Ghana': '🇬🇭',
  'Madagascar': '🇲🇬',
  'Cameroon': '🇨🇲',
  'Niger': '🇳🇪',
  'Burkina Faso': '🇧🇫',
  'Mali': '🇲🇱',
  'Malawi': '🇲🇼',
  'Zambia': '🇿🇲',
  'Somalia': '🇸🇴',
  'Senegal': '🇸🇳',
  'Chad': '🇹🇩',
  'Zimbabwe': '🇿🇼',
  'Guinea': '🇬🇳',
  'Rwanda': '🇷🇼',
  'Benin': '🇧🇯',
  'Tunisia': '🇹🇳',
  'Burundi': '🇧🇮',
  'Togo': '🇹🇬',
  'Sierra Leone': '🇸🇱',
  'Libya': '🇱🇾',
  'Liberia': '🇱🇷',
  'Central African Republic': '🇨🇫',
  'Central African Rep.': '🇨🇫',
  'Mauritania': '🇲🇷',
  'Eritrea': '🇪🇷',
  'Gambia': '🇬🇲',
  'Botswana': '🇧🇼',
  'Namibia': '🇳🇦',
  'Gabon': '🇬🇦',
  'Lesotho': '🇱🇸',
  'Guinea-Bissau': '🇬🇼',
  'Equatorial Guinea': '🇬🇶',
  'Equatorial Guinea (Malabo)': '🇬🇶',
  'Mauritius': '🇲🇺',
  'Eswatini': '🇸🇿',
  'Swaziland': '🇸🇿',
  'Djibouti': '🇩🇯',
  'Comoros': '🇰🇲',
  'Cabo Verde': '🇨🇻',
  'Cape Verde': '🇨🇻',
  'Sao Tome and Principe': '🇸🇹',
  'São Tomé and Príncipe': '🇸🇹',
  'Seychelles': '🇸🇨',
  'Congo': '🇨🇬',
  'Republic of the Congo': '🇨🇬',
  'Congo (Brazzaville)': '🇨🇬',
  'DR Congo': '🇨🇩',
  'Congo (Kinshasa)': '🇨🇩',
  'Congo, the Democratic Republic of the': '🇨🇩',
  'United Republic of Tanzania': '🇹🇿',
  'Tanzania': '🇹🇿',
  'Tanzania, United Republic of': '🇹🇿',
  'Western Sahara': '🇪🇭',
  'South Sudan': '🇸🇸',
  'South Sudan, Republic of': '🇸🇸',
  'Côte D\'Ivoire': '🇨🇮',
  'Cote d\'Ivoire': '🇨🇮',
  'Ivory Coast': '🇨🇮',
  
  // 其他地区
  'Greenland': '🇬🇱',
  'Greenland (GRL)': '🇬🇱',
  'GRL': '🇬🇱',
  'Faroe Islands': '🇫🇴',
  'Faroe Islands (FRO)': '🇫🇴',
  'FRO': '🇫🇴',
  'Åland Islands': '🇦🇽',
  'Åland': '🇦🇽',
  'Aland Islands': '🇦🇽',
  'Aland': '🇦🇽',
  'Gibraltar': '🇬🇮',
  'Gibraltar (GIB)': '🇬🇮',
  'GIB': '🇬🇮',
  'Isle of Man': '🇮🇲',
  'Isle of Man (IMN)': '🇮🇲',
  'IMN': '🇮🇲',
  'Jersey': '🇯🇪',
  'Jersey (JEY)': '🇯🇪',
  'JEY': '🇯🇪',
  'Guernsey': '🇬🇬',
  'Guernsey (GGY)': '🇬🇬',
  'GGY': '🇬🇬',
  'British Virgin Islands': '🇻🇬',
  'Virgin Islands, British': '🇻🇬',
  'Turks and Caicos Islands': '🇹🇨',
  'Turks and Caicos': '🇹🇨',
  'Turks & Caicos Islands': '🇹🇨',
  'Cayman Islands': '🇰🇾',
  'Cayman Islands (Cayman Islands)': '🇰🇾',
  'Cayman': '🇰🇾',
  'Montserrat': '🇲🇸',
  'Montserrat (MSR)': '🇲🇸',
  'MSR': '🇲🇸',
  'Anguilla': '🇦🇮',
  'Anguilla (AIA)': '🇦🇮',
  'AIA': '🇦🇮',
  'Bermuda': '🇧🇲',
  'Bermuda (BMU)': '🇧🇲',
  'BMU': '🇧🇲',
  'British Indian Ocean Territory': '🇮🇴',
  'BIOT': '🇮🇴',
  'British Indian Ocean Territory (BIOT)': '🇮🇴',
  'South Georgia and the South Sandwich Islands': '🇬🇸',
  'South Georgia and South Sandwich Islands': '🇬🇸',
  'South Georgia': '🇬🇸',
  'South Sandwich Islands': '🇬🇸',
  'Christmas Island': '🇨🇽',
  'Christmas Island (CXR)': '🇨🇽',
  'CXR': '🇨🇽',
  'Cocos Islands': '🇨🇨',
  'Cocos (Keeling) Islands': '🇨🇨',
  'Keeling Islands': '🇨🇨',
  'Cocos (Keeling) Islands (CCK)': '🇨🇨',
  'CCK': '🇨🇨',
  'Norfolk Island': '🇳🇫',
  'Norfolk Island (NFK)': '🇳🇫',
  'NFK': '🇳🇫',
  'Netherlands Antilles': '🇦🇳',
  'Netherlands Antilles (Nederlandse Antillen)': '🇦🇳',
  'Nederlandse Antillen': '🇦🇳',
  'Aruba': '🇦🇼',
  'Curaçao': '🇨🇼',
  'Curacao': '🇨🇼',
  'Curaçao (Kòrsou)': '🇨🇼',
  'Kòrsou': '🇨🇼',
  'Sint Maarten': '🇸🇽',
  'Sint Maarten (Dutch part)': '🇸🇽',
  'Sint Maarten (Sint Maarten)': '🇸🇽',
  'Bonaire': '🇧🇶',
  'Bonaire, Sint Eustatius and Saba': '🇧🇶',
  'Saba': '🇧🇶',
  'Sint Eustatius': '🇧🇶',
  'Caribbean Netherlands': '🇧🇶',
  'Saint Martin': '🇲🇫',
  'Saint Martin (French part)': '🇲🇫',
  'Collectivity of Saint Martin': '🇲🇫',
  'Saint Barthélemy': '🇧🇱',
  'Saint Barthelemy': '🇧🇱',
  'St. Barthelemy': '🇧🇱',
  'Saint Pierre and Miquelon': '🇵🇲',
  'Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)': '🇵🇲',
  'Saint-Pierre-et-Miquelon': '🇵🇲',
  'French Southern Territories': '🇹🇫',
  'French Southern and Antarctic Lands': '🇹🇫',
  'Terres australes et antarctiques françaises': '🇹🇫',
  'French Southern Territories (TAAF)': '🇹🇫',
  'TAAF': '🇹🇫',
  'Réunion': '🇷🇪',
  'Reunion': '🇷🇪',
  'Mayotte': '🇾🇹',
  'Martinique': '🇲🇶',
  'Guadeloupe': '🇬🇵',
  'United States Virgin Islands': '🇻🇮',
  'U.S. Virgin Islands': '🇻🇮',
  'US Virgin Islands': '🇻🇮',
  'Virgin Islands, U.S.': '🇻🇮',
  'Virgin Islands': '🇻🇮',
  'Puerto Rico': '🇵🇷',
  'Commonwealth of Puerto Rico': '🇵🇷',
  'Puerto Rico (Estado Libre Asociado de Puerto Rico)': '🇵🇷',
  'Estado Libre Asociado de Puerto Rico': '🇵🇷',
  'U.S. Minor Outlying Islands': '🇺🇲',
  'United States Minor Outlying Islands': '🇺🇲',
  'Minor Outlying Islands': '🇺🇲',
  'Heard Island and McDonald Islands': '🇭🇲',
  'Heard Island and McDonald Islands (HIMI)': '🇭🇲',
  'Heard Island and McDonald Mcdonald Islands': '🇭🇲',
  'McDonald Islands': '🇭🇲',
  'Heard Island': '🇭🇲',
  'Pitcairn Islands': '🇵🇳',
  'Pitcairn': '🇵🇳',
  'Pitcairn, Henderson, Ducie and Oeno Islands': '🇵🇳',
  'British Antarctic Territory': '🇦🇶',
  'British Antarctic': '🇦🇶',
  'Antarctica': '🇦🇶',
  'Antarctic': '🇦🇶',
  
  '_unknown': '🏳'
};

export const getCountryFlag = (country: string): string => {
  const mainCountry = country.split(',')[0].trim();
  return countryFlags[mainCountry] || countryFlags['_unknown'];
};